SKILL_SOURCES = {
    "Python":                  ("field", "coding_skill"),
    "DSA":                     ("field", "problem_solving"),
    "Git & GitHub":            ("tech", "git"),
    "SQL":                     ("tech", "sql"),
    "Machine Learning":        ("tech", "machine learning"),
    "Deep Learning":           ("tech", "deep learning"),
    "NumPy":                   ("tech", "numpy"),
    "Pandas":                  ("tech", "pandas"),
    "Deployment":              ("tech", "deployment"),
    "Docker":                  ("tech", "docker"),
    "Networking":              ("tech", "networking"),
    "Linux":                   ("tech", "linux"),
    "Wireshark":               ("tech", "wireshark"),
    "Nmap":                    ("tech", "nmap"),
    "Burp Suite":              ("tech", "burp"),
    "OWASP":                   ("tech", "owasp"),
    "Cloud Platforms":         ("tech", "cloud"),
    "System Design":           ("field", "problem_solving"),
    "DBMS":                    ("tech", "dbms"),
    "Statistics":              ("tech", "statistics"),
    "Research Writing":        ("derived", "research"),
    "Business Acumen":         ("derived", "business"),
    "Leadership":              ("derived", "business"),
    "Communication":           ("field", "communication"),
    "Teamwork":                ("field", "teamwork"),
    "Project Building":        ("field", "project_skill"),
    "HTML/CSS":                ("tech", "html"),
    "JavaScript":              ("tech", "javascript"),
    "React / Frontend Framework": ("tech", "react"),
    "Quantitative Aptitude":   ("field", "problem_solving"),
    "Reasoning Ability":       ("derived", "awareness"),
    "General Awareness":       ("derived", "awareness"),
    "Consistency & Discipline": ("field", "teamwork"),
}

CAREER_PATHS = {
    "Software Development / IT": {
        "emoji": "💻",
        "required_skills": {
            "Python": 80, "DSA": 85, "DBMS": 75,
            "System Design": 60, "Git & GitHub": 75, "SQL": 70,
        },
        "roadmap": [
            ("Month 1", ["Python", "Git & GitHub"]),
            ("Month 2", ["DSA"]),
            ("Month 3", ["DBMS", "SQL"]),
            ("Month 4", ["System Design Basics"]),
            ("Month 5", ["Build a Full-Stack Project"]),
            ("Month 6", ["Resume + Placement Prep"]),
        ],
        "certifications": [
            {"title": "Meta Front-End Developer", "difficulty": "Beginner",
                "duration": "7 months (self-paced)", "link": "https://www.coursera.org/professional-certificates/meta-front-end-developer"},
            {"title": "Microsoft Full-Stack Developer", "difficulty": "Intermediate",
                "duration": "6 months (self-paced)", "link": "https://learn.microsoft.com/en-us/training/"},
            {"title": "Oracle Java Certification", "difficulty": "Intermediate",
                "duration": "20 hrs", "link": "https://education.oracle.com/java-certification"},
        ],
        "projects": {
            "Beginner": [
                {"name": "To-Do List App", "tech": "HTML, CSS, JS",
                    "link": "https://github.com/search?q=todo+list+app"},
                {"name": "Portfolio Website", "tech": "HTML, CSS, JS",
                    "link": "https://github.com/search?q=portfolio+website+template"},
            ],
            "Intermediate": [
                {"name": "E-commerce Website", "tech": "Flask/Django, SQL",
                    "link": "https://github.com/search?q=ecommerce+website+flask"},
                {"name": "Chat Application", "tech": "WebSockets, Node.js",
                    "link": "https://github.com/search?q=realtime+chat+app"},
            ],
            "Advanced": [
                {"name": "Microservices-based Backend", "tech": "Docker, REST APIs",
                    "link": "https://github.com/search?q=microservices+project"},
                {"name": "Scalable Job Portal", "tech": "Full-Stack, SQL, Auth",
                    "link": "https://github.com/search?q=job+portal+full+stack"},
            ],
        },
        "companies": {
            "Dream": ["Google", "Amazon", "Microsoft", "Adobe"],
            "Good": ["TCS", "Infosys", "Wipro", "Capgemini"],
            "Easy Entry": ["Product Startups", "Local IT Firms", "Internship Programs"],
        },
        "salary": {"Fresher": "₹4-9 LPA", "Mid Level": "₹12-20 LPA", "Senior": "₹25+ LPA"},
        "internship_query": "Software Developer Intern",
    },

    "Data Science & Analytics": {
        "emoji": "📊",
        "required_skills": {
            "Python": 85, "Statistics": 80, "SQL": 80,
            "Machine Learning": 75, "DSA": 60, "Git & GitHub": 65,
        },
        "roadmap": [
            ("Month 1", ["Python", "Statistics"]),
            ("Month 2", ["SQL", "Git & GitHub"]),
            ("Month 3", ["Machine Learning"]),
            ("Month 4", ["Data Visualization Project"]),
            ("Month 5", ["Build a Capstone Dataset Project"]),
            ("Month 6", ["Resume + Placement Prep"]),
        ],
        "certifications": [
            {"title": "Google Data Analytics Certificate", "difficulty": "Beginner", "duration": "6 weeks",
                "link": "https://www.coursera.org/professional-certificates/google-data-analytics"},
            {"title": "IBM Data Science Professional Certificate", "difficulty": "Intermediate",
                "duration": "10 weeks", "link": "https://www.coursera.org/professional-certificates/ibm-data-science"},
            {"title": "Microsoft Power BI Data Analyst", "difficulty": "Beginner", "duration": "12 hrs",
                "link": "https://learn.microsoft.com/en-us/credentials/certifications/power-bi-data-analyst-associate/"},
        ],
        "projects": {
            "Beginner": [
                {"name": "Sales Data Dashboard", "tech": "Python, Pandas, Matplotlib",
                    "link": "https://github.com/search?q=sales+data+dashboard+python"},
                {"name": "Titanic Survival Analysis", "tech": "Python, Scikit-learn",
                    "link": "https://github.com/search?q=titanic+survival+prediction"},
            ],
            "Intermediate": [
                {"name": "Customer Churn Prediction", "tech": "Python, Pandas, XGBoost",
                    "link": "https://github.com/search?q=customer+churn+prediction"},
                {"name": "Movie Recommendation System", "tech": "Python, Collaborative Filtering",
                    "link": "https://github.com/search?q=movie+recommendation+system"},
            ],
            "Advanced": [
                {"name": "Real-time Analytics Pipeline", "tech": "Python, SQL, Airflow",
                    "link": "https://github.com/search?q=real+time+analytics+pipeline"},
                {"name": "Fraud Detection System", "tech": "Python, ML, Imbalanced Data",
                    "link": "https://github.com/search?q=fraud+detection+machine+learning"},
            ],
        },
        "companies": {
            "Dream": ["Google", "Amazon", "Netflix", "Microsoft"],
            "Good": ["TCS", "Wipro", "Mu Sigma", "Fractal Analytics"],
            "Easy Entry": ["Analytics Startups", "Local Data Firms", "Internship Programs"],
        },
        "salary": {"Fresher": "₹5-10 LPA", "Mid Level": "₹12-22 LPA", "Senior": "₹28+ LPA"},
        "internship_query": "Data Analyst Intern",
    },

    "Web Development": {
        "emoji": "🌐",
        "required_skills": {
            "HTML/CSS": 80, "JavaScript": 80, "React / Frontend Framework": 65,
            "SQL": 55, "Git & GitHub": 75, "DSA": 50,
        },
        "roadmap": [
            ("Month 1", ["HTML/CSS", "Git & GitHub"]),
            ("Month 2", ["JavaScript"]),
            ("Month 3", ["React / Frontend Framework"]),
            ("Month 4", ["Backend Basics", "SQL"]),
            ("Month 5", ["Build a Full-Stack Project"]),
            ("Month 6", ["Resume + Placement Prep"]),
        ],
        "certifications": [
            {"title": "freeCodeCamp Responsive Web Design", "difficulty": "Beginner",
                "duration": "300 hrs (self-paced)", "link": "https://www.freecodecamp.org/learn/2022/responsive-web-design/"},
            {"title": "Meta Front-End Developer", "difficulty": "Beginner",
                "duration": "7 months (self-paced)", "link": "https://www.coursera.org/professional-certificates/meta-front-end-developer"},
            {"title": "Meta Back-End Developer", "difficulty": "Intermediate",
                "duration": "8 months (self-paced)", "link": "https://www.coursera.org/professional-certificates/meta-back-end-developer"},
        ],
        "projects": {
            "Beginner": [
                {"name": "Personal Portfolio Website", "tech": "HTML, CSS, JS",
                    "link": "https://github.com/search?q=portfolio+website+template"},
                {"name": "Landing Page Clone", "tech": "HTML, CSS",
                    "link": "https://github.com/search?q=landing+page+clone"},
            ],
            "Intermediate": [
                {"name": "Blog Platform with Auth", "tech": "React, Node.js, JWT",
                    "link": "https://github.com/search?q=blog+platform+auth+react"},
                {"name": "Weather App with API", "tech": "JavaScript, REST API",
                    "link": "https://github.com/search?q=weather+app+javascript"},
            ],
            "Advanced": [
                {"name": "Full-Stack E-commerce Site", "tech": "React, Node.js, SQL, Payments",
                    "link": "https://github.com/search?q=fullstack+ecommerce+react"},
                {"name": "Real-time Collaborative Editor", "tech": "WebSockets, React",
                    "link": "https://github.com/search?q=realtime+collaborative+editor"},
            ],
        },
        "companies": {
            "Dream": ["Google", "Meta", "Amazon", "Adobe"],
            "Good": ["TCS", "Infosys", "Zoho", "Freshworks"],
            "Easy Entry": ["Web Agencies", "Freelance / Local Businesses", "Internship Programs"],
        },
        "salary": {"Fresher": "₹3.5-8 LPA", "Mid Level": "₹10-18 LPA", "Senior": "₹22+ LPA"},
        "internship_query": "Web Developer Intern",
    },

    "Artificial Intelligence & Emerging Technologies": {
        "emoji": "✨",
        "required_skills": {
            "Python": 65, "Machine Learning": 60, "Communication": 70,
            "Business Acumen": 55, "Git & GitHub": 50, "Deep Learning": 45,
        },
        "roadmap": [
            ("Month 1", ["Python", "AI Landscape Overview"]),
            ("Month 2", ["Machine Learning Fundamentals"]),
            ("Month 3", ["Explore GenAI & Prompt Engineering"]),
            ("Month 4", ["Build a Project Using an LLM/GenAI API"]),
            ("Month 5", ["Write / Present on an Emerging Tech Trend"]),
            ("Month 6", ["Resume + Portfolio"]),
        ],
        "certifications": [
            {"title": "Google AI Essentials", "difficulty": "Beginner", "duration": "8 hrs",
                "link": "https://www.coursera.org/learn/google-ai-essentials"},
            {"title": "Microsoft AI Fundamentals (AI-900)", "difficulty": "Beginner", "duration": "15 hrs",
             "link": "https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-fundamentals/"},
            {"title": "Generative AI for Everyone", "difficulty": "Beginner", "duration": "6 hrs",
                "link": "https://www.coursera.org/learn/generative-ai-for-everyone"},
            {"title": "Prompt Engineering Specialization", "difficulty": "Intermediate",
                "duration": "4 weeks", "link": "https://www.coursera.org/specializations/prompt-engineering"},
        ],
        "projects": {
            "Beginner": [
                {"name": "Chatbot Using an LLM API", "tech": "Python, LLM API",
                    "link": "https://github.com/search?q=llm+chatbot+python"},
                {"name": "AI Content Summarizer", "tech": "Python, NLP",
                    "link": "https://github.com/search?q=ai+text+summarizer"},
            ],
            "Intermediate": [
                {"name": "GenAI-powered Study Assistant", "tech": "Python, Flask, LLM API",
                    "link": "https://github.com/search?q=genai+study+assistant"},
                {"name": "AI Image Generator App", "tech": "Python, Diffusion API",
                    "link": "https://github.com/search?q=ai+image+generator+app"},
            ],
            "Advanced": [
                {"name": "Multi-agent AI Workflow System", "tech": "Python, Agent Frameworks",
                    "link": "https://github.com/search?q=multi+agent+ai+workflow"},
                {"name": "Custom RAG-based Knowledge Assistant", "tech": "Python, Vector DB, LLM API",
                    "link": "https://github.com/search?q=rag+knowledge+assistant"},
            ],
        },
        "companies": {
            "Dream": ["OpenAI", "Anthropic", "Google DeepMind", "Microsoft AI"],
            "Good": ["TCS AI Labs", "Wipro AI Practice", "Infosys AI", "Accenture AI"],
            "Easy Entry": ["AI Startups", "Innovation Labs", "Internship Programs"],
        },
        "salary": {"Fresher": "₹5-11 LPA", "Mid Level": "₹14-22 LPA", "Senior": "₹28+ LPA"},
        "internship_query": "AI Emerging Technologies Intern",
    },

    "Management / MBA": {
        "emoji": "📈",
        "required_skills": {
            "Business Acumen": 75, "Communication": 85, "Leadership": 75,
            "Quantitative Aptitude": 60, "Teamwork": 70, "Project Building": 55,
        },
        "roadmap": [
            ("Month 1", ["Communication & Business Fundamentals"]),
            ("Month 2", ["Quantitative Aptitude (CAT/MAT Prep)"]),
            ("Month 3", ["Case Studies & GD Practice"]),
            ("Month 4", ["Take a Leadership Role (Club / Fest / Committee)"]),
            ("Month 5", ["Internship or Live Business Project"]),
            ("Month 6", ["MBA Application / Placement Prep"]),
        ],
        "certifications": [
            {"title": "Google Project Management Certificate", "difficulty": "Beginner",
                "duration": "6 months (self-paced)", "link": "https://www.coursera.org/professional-certificates/google-project-management"},
            {"title": "Wharton Business Foundations Specialization", "difficulty": "Beginner",
                "duration": "5 months (self-paced)", "link": "https://www.coursera.org/specializations/wharton-fundamentals"},
            {"title": "CAT / MBA Aptitude Prep", "difficulty": "Intermediate",
                "duration": "Self-paced", "link": "https://unacademy.com/goal/cat-preparation/KSNAG"},
        ],
        "projects": {
            "Beginner": [
                {"name": "Organize a College Event", "tech": "Planning, Coordination",
                    "link": "https://github.com/search?q=event+management+case+study"},
                {"name": "Business Case Study Analysis", "tech": "Case Study Frameworks",
                    "link": "https://github.com/search?q=business+case+study+analysis"},
            ],
            "Intermediate": [
                {"name": "Lead a Club or Committee Project", "tech": "Leadership, Team Management",
                    "link": "https://github.com/search?q=student+leadership+project"},
                {"name": "Market Research Report", "tech": "Market Research, Excel",
                    "link": "https://github.com/search?q=market+research+report+template"},
            ],
            "Advanced": [
                {"name": "Live Consulting Project for a Local Business", "tech": "Strategy, Analysis",
                    "link": "https://github.com/search?q=student+consulting+project"},
                {"name": "Startup Business Plan Competition", "tech": "Business Planning, Pitching",
                    "link": "https://github.com/search?q=business+plan+competition+template"},
            ],
        },
        "companies": {
            "Dream": ["McKinsey & Company", "BCG", "Bain & Company", "Top B-School MBA Programs"],
            "Good": ["Deloitte", "EY", "KPMG", "PwC"],
            "Easy Entry": ["Local Businesses (Management Trainee)", "Campus Placement Cells", "Family Business"],
        },
        "salary": {"Fresher": "₹4-8 LPA", "Mid Level": "₹12-25 LPA (post-MBA)", "Senior": "₹30+ LPA"},
        "internship_query": "Management Trainee Intern",
    },

    "Government / Public Sector Opportunities": {
        "emoji": "🏛️",
        "required_skills": {
            "Quantitative Aptitude": 75, "Reasoning Ability": 70, "General Awareness": 65,
            "Communication": 60, "Consistency & Discipline": 55,
        },
        "roadmap": [
            ("Month 1", ["Build a Daily Current Affairs Habit"]),
            ("Month 2", ["Quantitative Aptitude & Reasoning Practice"]),
            ("Month 3", [
             "Choose Target Exam (UPSC / SSC / Banking / State PSC)"]),
            ("Month 4", ["Subject-wise Preparation + Sectional Mock Tests"]),
            ("Month 5", ["Answer Writing / Interview Practice"]),
            ("Month 6", ["Full-length Mock Tests + Previous Year Papers"]),
        ],
        "certifications": [
            {"title": "SSC CGL Foundation Course", "difficulty": "Beginner",
                "duration": "Self-paced", "link": "https://testbook.com/ssc-cgl"},
            {"title": "UPSC CSE Foundation", "difficulty": "Advanced",
                "duration": "Self-paced", "link": "https://www.drishtiias.com/"},
            {"title": "Banking Exams Prep (IBPS/SBI)", "difficulty": "Intermediate",
             "duration": "Self-paced", "link": "https://www.oliveboard.in/"},
            {"title": "Static GK & Current Affairs", "difficulty": "Beginner",
                "duration": "Self-paced", "link": "https://www.adda247.com/"},
        ],
        "projects": {
            "Beginner": [
                {"name": "Daily Newspaper Reading + Notes", "tech": "Current Affairs",
                    "link": "https://www.adda247.com/current-affairs/"},
                {"name": "Basic Numerical Ability Practice",
                    "tech": "Quantitative Aptitude", "link": "https://testbook.com/"},
            ],
            "Intermediate": [
                {"name": "Sectional Mock Tests", "tech": "Reasoning, Aptitude",
                    "link": "https://www.oliveboard.in/"},
                {"name": "Previous Year Paper Analysis", "tech": "Exam Analysis",
                    "link": "https://www.drishtiias.com/previous-year-papers"},
            ],
            "Advanced": [
                {"name": "Full-Length Mock Test Series",
                    "tech": "Timed Practice", "link": "https://testbook.com/"},
                {"name": "Mock Interview / Personality Test Practice",
                    "tech": "Interview Skills", "link": "https://www.drishtiias.com/"},
            ],
        },
        "companies": {
            "Dream": ["UPSC (IAS / IPS / IFS)", "RBI Grade B", "State PSC (Top Posts)", "Indian Forest Service"],
            "Good": ["SSC CGL", "Banking (IBPS PO)", "Railway RRB", "State Level Exams"],
            "Easy Entry": ["SSC CHSL", "Clerical Cadre Jobs", "Local Govt Vacancies"],
        },
        "salary": {"Fresher": "₹25,000-45,000/month (Pay Level 6-7)", "Mid Level": "₹56,100-1,00,000+/month (Pay Level 9-11)", "Senior": "₹1,44,200-2,25,000/month (Pay Level 13-15)"},
        "internship_query": "Government Internship",
    },

    "AI / ML Engineer": {
        "emoji": "🤖",
        "required_skills": {
            "Python": 90, "DSA": 78, "Machine Learning": 85,
            "Deployment": 68, "Docker": 55, "SQL": 65,
        },
        "roadmap": [
            ("Month 1", ["Python", "Git & GitHub"]),
            ("Month 2", ["DSA", "SQL"]),
            ("Month 3", ["Machine Learning"]),
            ("Month 4", ["Deep Learning"]),
            ("Month 5", ["Docker + Deploy a Model"]),
            ("Month 6", ["Resume + Placement Prep"]),
        ],
        "certifications": [
            {"title": "IBM AI Fundamentals", "difficulty": "Beginner", "duration": "10 hrs",
                "link": "https://www.ibm.com/training/badge/ai-fundamentals"},
            {"title": "Google AI Essentials", "difficulty": "Beginner", "duration": "8 hrs",
                "link": "https://www.coursera.org/learn/google-ai-essentials"},
            {"title": "AWS Machine Learning Foundations", "difficulty": "Intermediate",
                "duration": "12 hrs", "link": "https://aws.amazon.com/training/learn-about/machine-learning/"},
            {"title": "TensorFlow Developer Certificate", "difficulty": "Advanced",
                "duration": "20 hrs", "link": "https://www.tensorflow.org/certificate"},
        ],
        "projects": {
            "Beginner": [
                {"name": "Student Performance Predictor", "tech": "Python, Scikit-learn, Pandas",
                    "link": "https://github.com/search?q=student+performance+predictor+ml"},
                {"name": "Spam Classifier", "tech": "Python, NLP",
                    "link": "https://github.com/search?q=spam+classifier+nlp"},
            ],
            "Intermediate": [
                {"name": "Model Deployment with Flask API", "tech": "Python, Flask, Docker",
                    "link": "https://github.com/search?q=ml+model+deployment+flask"},
                {"name": "Resume Analyzer", "tech": "Python, NLP, Spacy",
                    "link": "https://github.com/search?q=resume+analyzer+nlp"},
            ],
            "Advanced": [
                {"name": "End-to-End MLOps Pipeline", "tech": "Python, Docker, CI/CD",
                    "link": "https://github.com/search?q=mlops+pipeline+project"},
                {"name": "Medical Diagnosis System", "tech": "Python, TensorFlow, CNN",
                    "link": "https://github.com/search?q=medical+diagnosis+deep+learning"},
            ],
        },
        "companies": {
            "Dream": ["NVIDIA", "OpenAI", "Google DeepMind", "Meta AI"],
            "Good": ["TCS Research", "Persistent Systems", "Cognizant", "Infosys"],
            "Easy Entry": ["AI Startups", "Local AI Firms", "Internship Programs"],
        },
        "salary": {"Fresher": "₹6-13 LPA", "Mid Level": "₹16-26 LPA", "Senior": "₹32+ LPA"},
        "internship_query": "Machine Learning Engineer Intern",
    },

    "Cybersecurity Specialist": {
        "emoji": "🛡️",
        "required_skills": {
            "Networking": 85, "Linux": 80, "Wireshark": 70,
            "Nmap": 70, "Burp Suite": 65, "OWASP": 60,
        },
        "roadmap": [
            ("Month 1", ["Networking", "Linux"]),
            ("Month 2", ["Wireshark", "Nmap"]),
            ("Month 3", ["OWASP Top 10"]),
            ("Month 4", ["Burp Suite", "Web App Pentesting"]),
            ("Month 5", ["TryHackMe / HackTheBox Practice"]),
            ("Month 6", ["Resume + Placement Prep"]),
        ],
        "certifications": [
            {"title": "Cisco Networking Basics", "difficulty": "Beginner",
                "duration": "20 hrs", "link": "https://www.netacad.com/courses/networking"},
            {"title": "Google Cybersecurity Certificate", "difficulty": "Beginner",
                "duration": "6 months (self-paced)", "link": "https://www.coursera.org/professional-certificates/google-cybersecurity"},
            {"title": "TryHackMe Learning Paths", "difficulty": "Intermediate",
                "duration": "Self-paced", "link": "https://tryhackme.com/paths"},
            {"title": "HackTheBox Academy", "difficulty": "Advanced",
                "duration": "Self-paced", "link": "https://academy.hackthebox.com/"},
        ],
        "projects": {
            "Beginner": [
                {"name": "Home Lab Network Setup", "tech": "VirtualBox, pfSense",
                    "link": "https://github.com/search?q=home+lab+network+security"},
                {"name": "Password Strength Checker", "tech": "Python",
                    "link": "https://github.com/search?q=password+strength+checker"},
            ],
            "Intermediate": [
                {"name": "Vulnerability Scanner", "tech": "Python, Nmap API",
                    "link": "https://github.com/search?q=vulnerability+scanner+python"},
                {"name": "Phishing Detection Tool", "tech": "Python, ML",
                    "link": "https://github.com/search?q=phishing+detection+ml"},
            ],
            "Advanced": [
                {"name": "Web App Penetration Test Report", "tech": "Burp Suite, OWASP ZAP",
                    "link": "https://github.com/search?q=web+app+pentest+report"},
                {"name": "SOC / SIEM Simulation Lab", "tech": "Splunk, ELK Stack",
                    "link": "https://github.com/search?q=soc+siem+lab+project"},
            ],
        },
        "companies": {
            "Dream": ["CrowdStrike", "Palo Alto Networks", "Google", "Microsoft"],
            "Good": ["TCS Cybersecurity", "Wipro", "Infosys", "HCL"],
            "Easy Entry": ["Security Startups", "Local IT Firms", "Internship Programs"],
        },
        "salary": {"Fresher": "₹4-9 LPA", "Mid Level": "₹12-22 LPA", "Senior": "₹28+ LPA"},
        "internship_query": "Cyber Security Intern",
    },

    "Research & Higher Studies": {
        "emoji": "🔬",
        "required_skills": {
            "Statistics": 85, "Python": 75, "Research Writing": 80,
            "Machine Learning": 65, "DSA": 55, "Communication": 70,
        },
        "roadmap": [
            ("Month 1", ["Python", "Statistics"]),
            ("Month 2", ["Read & Summarize 5 Research Papers"]),
            ("Month 3", ["Machine Learning Fundamentals"]),
            ("Month 4", ["Research Writing & LaTeX"]),
            ("Month 5", ["Write & Submit a Paper (e.g. IJFMR)"]),
            ("Month 6", ["Resume + Research Portfolio"]),
        ],
        "certifications": [
            {"title": "IBM AI Fundamentals", "difficulty": "Beginner", "duration": "10 hrs",
                "link": "https://www.ibm.com/training/badge/ai-fundamentals"},
            {"title": "Coursera Research Methods Specialization", "difficulty": "Intermediate",
                "duration": "4 weeks", "link": "https://www.coursera.org/browse/social-sciences/research-methods"},
            {"title": "Google AI Essentials", "difficulty": "Beginner", "duration": "8 hrs",
                "link": "https://www.coursera.org/learn/google-ai-essentials"},
        ],
        "projects": {
            "Beginner": [
                {"name": "Literature Review Summary Tool", "tech": "Python, NLP",
                    "link": "https://github.com/search?q=literature+review+nlp+tool"},
                {"name": "Dataset Exploration Notebook", "tech": "Python, Pandas",
                    "link": "https://github.com/search?q=exploratory+data+analysis+notebook"},
            ],
            "Intermediate": [
                {"name": "Reproduce a Published Paper's Results", "tech": "Python, ML",
                    "link": "https://github.com/search?q=paper+reproduction+ml"},
                {"name": "Survey Paper on Emerging Tech", "tech": "Research Writing",
                    "link": "https://github.com/search?q=survey+paper+ai"},
            ],
            "Advanced": [
                {"name": "Original Research Paper Submission", "tech": "LaTeX, Statistics",
                    "link": "https://github.com/search?q=research+paper+latex+template"},
                {"name": "Conference-style Poster Project", "tech": "Data Analysis, Design",
                    "link": "https://github.com/search?q=research+poster+template"},
            ],
        },
        "companies": {
            "Dream": ["Google Research", "Microsoft Research", "IITs / IISc Labs", "Meta AI Research"],
            "Good": ["TCS Research", "Wadhwani AI", "R&D Labs of PSUs", "University Labs"],
            "Easy Entry": ["Research Internships", "Journal Publication Programs", "Local University Projects"],
        },
        "salary": {"Fresher": "₹5-10 LPA (or stipend-based)", "Mid Level": "₹14-22 LPA", "Senior": "₹26+ LPA"},
        "internship_query": "Research Intern",
    },

    "Entrepreneurship / Startup": {
        "emoji": "🚀",
        "required_skills": {
            "Business Acumen": 80, "Communication": 85, "Teamwork": 75,
            "Project Building": 75, "Python": 50, "System Design": 55,
        },
        "roadmap": [
            ("Month 1", ["Validate a Problem & Idea"]),
            ("Month 2", ["Build an MVP"]),
            ("Month 3", ["Business & Pitching Basics"]),
            ("Month 4", ["Get First 10 Users / Customers"]),
            ("Month 5", ["Iterate Based on Feedback"]),
            ("Month 6", ["Pitch Deck + Incubator Applications"]),
        ],
        "certifications": [
            {"title": "Google Digital Marketing & E-commerce", "difficulty": "Beginner",
                "duration": "6 months (self-paced)", "link": "https://www.coursera.org/professional-certificates/google-digital-marketing-ecommerce"},
            {"title": "Wharton Entrepreneurship Specialization", "difficulty": "Intermediate",
                "duration": "4 months (self-paced)", "link": "https://www.coursera.org/specializations/wharton-entrepreneurship"},
            {"title": "Y Combinator Startup School", "difficulty": "Intermediate",
                "duration": "Self-paced", "link": "https://www.startupschool.org/"},
        ],
        "projects": {
            "Beginner": [
                {"name": "Landing Page + Waitlist", "tech": "HTML/CSS, Forms",
                    "link": "https://github.com/search?q=startup+landing+page+waitlist"},
                {"name": "Simple SaaS MVP", "tech": "Flask/Django",
                    "link": "https://github.com/search?q=saas+mvp+starter"},
            ],
            "Intermediate": [
                {"name": "Marketplace App (Buyers/Sellers)", "tech": "Full-Stack, Payments",
                 "link": "https://github.com/search?q=marketplace+app+project"},
                {"name": "Subscription Billing System", "tech": "Stripe API, Backend",
                    "link": "https://github.com/search?q=subscription+billing+system"},
            ],
            "Advanced": [
                {"name": "Multi-tenant SaaS Platform", "tech": "Full-Stack, Cloud",
                    "link": "https://github.com/search?q=multi+tenant+saas+platform"},
                {"name": "Pitch-ready Product with Analytics", "tech": "Full-Stack, Analytics",
                    "link": "https://github.com/search?q=startup+analytics+dashboard"},
            ],
        },
        "companies": {
            "Dream": ["Y Combinator", "Sequoia-backed Startups", "Own Startup", "Top Accelerators"],
            "Good": ["College Incubation Cells", "State Startup Missions", "Angel-funded Startups"],
            "Easy Entry": ["Campus Entrepreneurship Cells", "Local Hackathons", "Bootstrapped Side Projects"],
        },
        "salary": {"Fresher": "Variable / Bootstrapped", "Mid Level": "Depends on Funding/Revenue", "Senior": "Equity + Revenue Share"},
        "internship_query": "Startup Founder's Office Intern",
    },
}
